name: Tests
on: [push, pull_request]
jobs:
  test-format:
    name: 'Code format check'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/kint-twig-setup
        name: Kint twig setup
        with:
          php-version: 8.4
          twig-version: 3
      - run: |
          composer format
          git status
          git diff-files --quiet --exit-code
        env:
          PHP_CS_FIXER_IGNORE_ENV: 1
  test-static:
    name: 'Static analysis check'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/kint-twig-setup
        name: Kint twig setup
        with:
          php-version: 8.4
          twig-version: 3
      - run: composer analyze
  test-basic:
    name: 'Basic test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/kint-twig-setup
        name: Kint twig setup
        with:
          php-version: 8.4
          twig-version: 3
      - run: php ./vendor/bin/phpunit tests
        env:
          MYSQLI_HOST: localhost:${{ job.services.mysql.ports['3306'] }}
  tests:
    name: 'PHP ${{ matrix.php-versions }} Twig ${{ matrix.twig }} tests'
    needs:
      - test-format
      - test-static
      - test-basic
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.php-versions == '8.5' }}
    strategy:
      fail-fast: false
      matrix:
        php-versions:
          - 7.4
          - 8.0
          - 8.1
          - 8.2
          - 8.3
          - 8.4
          - 8.5
        twig:
          - 2
          - 3
        exclude:
          # Twig 3 doesn't support < 8.1
          - php-versions: 7.4
            twig: 3
          - php-versions: 8.0
            twig: 3
          # Twig 2 is EOL and breaks in 8.4+
          - php-versions: 8.4
            twig: 2
          - php-versions: 8.5
            twig: 2
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/kint-twig-setup
        name: Kint twig setup
        with:
          php-version: ${{ matrix.php-versions }}
          twig-version: ${{ matrix.twig }}
      - run: php ./vendor/bin/phpunit --no-coverage tests
