name: Tests
on: [push, pull_request]
jobs:
  test-format:
    name: 'Code format check'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
      - uses: actions/cache@v2
        id: vendor-caches
        with:
          path: |
            ./vendor
          key: 3-${{ hashFiles('./composer.lock') }}
      - run: composer install
        if: steps.vendor-caches.outputs.cache-hit != 'true'
      - run: composer format
      - run: git status
      - run: git diff-files --quiet --exit-code
  test-static:
    name: 'Static analysis check'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
      - uses: actions/cache@v2
        id: vendor-caches
        with:
          path: |
            ./vendor
          key: 3-${{ hashFiles('./composer.lock') }}
      - run: composer install
        if: steps.vendor-caches.outputs.cache-hit != 'true'
      - run: composer analyze
  test-basic:
    name: 'Basic test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
      - uses: actions/cache@v2
        id: vendor-caches
        with:
          path: |
            ./vendor
          key: 3-${{ hashFiles('./composer.lock') }}
      - run: composer install
        if: steps.vendor-caches.outputs.cache-hit != 'true'
      - run: php ./vendor/bin/phpunit tests
        env:
          MYSQLI_HOST: localhost:${{ job.services.mysql.ports['3306'] }}
  tests:
    name: 'PHP ${{ matrix.php-versions }} Twig ${{ matrix.twig }} tests'
    needs:
      - test-format
      - test-static
      - test-basic
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions:
          - 7.4
          - 8.0
          - 8.1
          - 8.2
          - 8.3
        twig:
          - 2
          - 3
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
      - uses: actions/cache@v2
        id: vendor-caches
        with:
          path: |
            ./vendor
          key: ${{ matrix.twig }}-${{ hashFiles('./composer.lock') }}
      - run: composer install
        if: steps.vendor-caches.outputs.cache-hit != 'true'
      - run: composer require twig/twig ^${{ matrix.twig }}
        if: steps.vendor-caches.outputs.cache-hit != 'true'
      - run: php ./vendor/bin/phpunit --no-coverage tests
  old-tests:
    name: 'PHP ${{ matrix.php-versions }} Twig ${{ matrix.twig }} tests'
    needs:
      - test-format
      - test-static
      - test-basic
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions:
          - 7.2
          - 7.3
        twig:
          - 2
          - 3
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
      - uses: actions/cache@v2
        id: vendor-caches
        with:
          path: |
            ./vendor
          key: old-${{ matrix.twig }}-${{ hashFiles('./composer.lock') }}
      - run: composer remove --dev friendsofphp/php-cs-fixer phpunit/phpunit phpspec/prophecy-phpunit vimeo/psalm
        if: steps.vendor-caches.outputs.cache-hit != 'true'
      - run: composer config platform.php 7.2.9
        if: steps.vendor-caches.outputs.cache-hit != 'true'
      - run: composer require twig/twig ^${{ matrix.twig }}
        if: steps.vendor-caches.outputs.cache-hit != 'true'
      - run: composer require --dev phpunit/phpunit ^7
        if: steps.vendor-caches.outputs.cache-hit != 'true'
      - run: php ./vendor/bin/phpunit --no-coverage tests
  older-tests:
    name: 'PHP 7.1 Twig 2 tests'
    needs:
      - test-format
      - test-static
      - test-basic
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.1
      - uses: actions/cache@v2
        id: vendor-caches
        with:
          path: |
            ./vendor
          key: older-${{ hashFiles('./composer.lock') }}
      - run: composer remove --dev friendsofphp/php-cs-fixer phpunit/phpunit phpspec/prophecy-phpunit vimeo/psalm
        if: steps.vendor-caches.outputs.cache-hit != 'true'
      - run: composer config platform.php 7.1.3
        if: steps.vendor-caches.outputs.cache-hit != 'true'
      - run: composer require twig/twig ^2
        if: steps.vendor-caches.outputs.cache-hit != 'true'
      - run: composer require --dev phpunit/phpunit ^7
        if: steps.vendor-caches.outputs.cache-hit != 'true'
      - run: php ./vendor/bin/phpunit --no-coverage tests
